import { randomBytes, scrypt, timingSafeEqual } from "node:crypto";

const KEY_LENGTH = 64;
const SCHEME = "scrypt";
/** Dots, not dollars: `$` is expanded away when a hash is pasted into .env.local. */
const SEPARATOR = ".";

async function derive(password: string, salt: Buffer, keyLength = KEY_LENGTH): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    scrypt(password, salt, keyLength, (error, derivedKey) =>
      error ? reject(error) : resolve(derivedKey as Buffer),
    );
  });
}

/** Format: `scrypt.<salt base64url>.<hash base64url>`. */
export async function hashPassword(password: string): Promise<string> {
  const salt = randomBytes(16);
  const derived = await derive(password, salt);
  return [SCHEME, salt.toString("base64url"), derived.toString("base64url")].join(SEPARATOR);
}

export async function verifyPassword(password: string, stored: string): Promise<boolean> {
  // `$` is accepted so hashes generated by earlier scripts keep working.
  const [scheme, saltPart, hashPart] = stored.split(/[.$]/);
  if (scheme !== SCHEME || !saltPart || !hashPart) return false;

  try {
    const expected = Buffer.from(hashPart, "base64url");
    const derived = await derive(password, Buffer.from(saltPart, "base64url"), expected.length);
    return derived.length === expected.length && timingSafeEqual(derived, expected);
  } catch {
    return false;
  }
}
